### ISSUE TITLE
Twitter logo update required in the footer

### ISSUE THREAD

**Issue by tmsagarofficial** [jlopp/lopp.net#1017]
I would like to point out that the logo of Twitter needs to be replaced with X from the already existing bird icon. 
Pls, let me know @jlopp .
I would love to work on this.

**Comment by jlopp** [comment]
This is tricky because I generate custom font files for the icons via https://icomoon.io/app/#/select

I also need to add one for nostr https://github.com/jlopp/lopp.net/issues/997
