### ISSUE TITLE
Proposal to add the F1X Bitcoin Music Video to the list

### ISSUE THREAD

**Issue by dundomaroye** [jlopp/lopp.net#1029]
https://github.com/jlopp/lopp.net/blame/d74456d57cc0d40b3e3e0a9eef88e09e7362430b/bitcoin-information/art-music.html#L160

Thank you for keeping a great list of Bitcoin resources, including art and music. 
I'd like to propose an addition, The F1X - released on Bitcoin genesis anniversary. A song that tells a story of Bitcoin's genesis, and why we showed up in the first place. 
It has a music video that amplifies the story. 
https://youtu.be/NPkX5xexAwU?si=ONmsbzkfviNBwfWO

**Comment by jlopp** [comment]
Might make sense to add the F1X playlist https://www.youtube.com/watch?v=_W2DAB8L-20&list=PLeQO3eO10Uz1ZC-RhsUaxajWq3GUuWxHM

**Comment by dundomaroye** [comment]
Agreed!
