### ISSUE TITLE
Add article to Bitcoin History section

### ISSUE THREAD

**Issue by Fiach-Dubh** [jlopp/lopp.net#1039]
Hello there,

I'd like to request this article be added to the Bitcoin History section of your website (https://www.lopp.net/bitcoin-information/history.html)

https://stacker.news/items/458544/r/BITC0IN

or this medium link with the same article:

https://medium.com/p/fad9f5550659

subheading suggestion: An Examination of November 2008 Draft Bitcoin Code 

Thank you for your consideration.

**Comment by jlopp** [comment]
Interesting article; thanks!
