### ISSUE TITLE
Bitcoin Dev Project (BDP) Links

### ISSUE THREAD

**Issue by satsie** [jlopp/lopp.net#1106]
The [Bitcoin Dev Project](https://bitcoindevs.xyz) (BDP) has a growing list of tools and educational resources for existing and aspiring BOSS (bitcoin + FOSS / bitcoin open source software) developers. I briefly looked at the your list on https://bitcoin.page and saw at least one of the BDP projects listed (Warnet). 

I'd like to make a PR to add more. I think it would be best to make a PR with links to each individual project ([ChatBTC](https://chat.bitcoinsearch.xyz/), [Bitcoin TLDR](https://tldr.bitcoinsearch.xyz/), [Good First Issues](https://bitcoindevs.xyz/good-first-issues), etc.) especially since they each have their own website. However I wanted to check with you first in case you preferred a PR with a single link to https://bitcoindevs.xyz.

Let me know which you prefer and I'll work on it!

**Comment by jlopp** [comment]
Separate links to each project all in one PR sounds fine to me.
