### ISSUE TITLE
Add new site

### ISSUE THREAD

**Issue by coinlore** [jlopp/lopp.net#157]
Hello,

May I ask to add coinlore.com, it contains lot of information for beginners and professionals.

Have own DB own algorithm to calculate prices from over 170 exchanges

It have

APi,
Widget,
Technical indicators,
Performance data, 
Team information for coins, 
News + Videos for coins and global, 
Historical ICO information for coins
Coin explain videos
Social Stats
Converter and much much more.

Thanks

**Comment by jlopp** [comment]
This looks like a pretty new site, I've never heard of it, and looks quite similar to most other coin listing sites. I try not to link too many similar sites on my directory, so in order for this to get added I'd want it to become more popular / useful than the currently linked indexes.
