### ISSUE TITLE
What section do slides on bitcoin scripts fall ?

### ISSUE THREAD

**Issue by prahaladbelavadi** [jlopp/lopp.net#172]
There is a little ambiguity on what section [slides](https://docs.google.com/presentation/d/1AjH4672eeUWEvM5a2ke1YLuJLpvRKBeHwrhMTwXlXGg/edit?usp=sharing) fall under ?

The slides are on bitcoin scripts. Would it be appropriate for them to be placed under developer tools or deep dive technical resources section ? What would you recommend ? @jlopp

**Comment by prahaladbelavadi** [comment]
Update: 
I reached out to @physicsdude over twitter and he does not have audio/video of the event.

We'll have to decide if the slides alone would represent useful content or if it is indispensable without audio or video.

Reference: 
- https://twitter.com/physic/status/1067878728775028736

**Comment by jlopp** [comment]
Given that  there are several other more comprehensive resources in the "technical deep dive" section I don't think that these slides offer any additional value to link from there.
