### ISSUE TITLE
Add blog, decide category

### ISSUE THREAD

**Issue by nopara73** [jlopp/lopp.net#18]
I'd like to create a PR to add my blog: https://medium.com/@nopara73  

However its content is 80% privacy, so I am not sure if the blogs category or the privacy category should be aimed.

**Comment by jlopp** [comment]
Yeah this can be tricky sometimes because some sections are topical while others are grouped by communications medium... I'd put it under the blog section though.

**Comment by nopara73** [comment]
Thinking twice about it, it's a personal blog, where the privacy writing just happened to be my main point of interest and it cannot be guaranteed it'll stay like this forever.  
https://github.com/jlopp/lopp.net/pull/19
