### ISSUE TITLE
Remove CoinTelegraph, Add Merklereport

### ISSUE THREAD

**Issue by junseth** [jlopp/lopp.net#195]
Full disclosure, Merklereport.com is mine. But I think we've got a great curated bitcoin site that does a great job of combing through most of these sources and gives the relevant content. We also find content that isn't in these mainstream Bitcoin publications.

I would also remove CoinTelegraph from this list. They traffic in re-caps, rarely (if ever) break stories, and I find their stories to often be of questionable merit.

**Comment by jlopp** [comment]
Cool, haven't seen this - bonus points for night mode. Agreed that CT is kinda sketchy...

**Comment by Sjors** [comment]
I'm also for adding MerkleReport. Disclaimer: I'm part of the massive (or well, five people?) MerkleReport Shill Army.
