### ISSUE TITLE
Add visualized fork history "mapofcoins"

### ISSUE THREAD

**Issue by NicolasSchmutz** [jlopp/lopp.net#30]
Suggestion for your bitcoin resource list: http://mapofcoins.com/bitcoin

A great tool to explore the visualized history of cryptocurrencies and its forks.

**Comment by jlopp** [comment]
I'm a bit conflicted on this. I'm aware of the site and have considered adding it previously, but the data is old - it hasn't been updated since 2015. If it was kept up to date then I'd definitely add it.

**Comment by NicolasSchmutz** [comment]
True, I haven't noticed that. There are also no news on [facebook](https://www.facebook.com/pg/mapofcoins/posts/?ref=page_internal) since then.
I dropped them a messages and asked if they plan to update the site or if they discontinue the project.
