### ISSUE TITLE
Request to add essaysonbitcoin.com

### ISSUE THREAD

**Issue by johnnygleeson** [jlopp/lopp.net#32]
Hey Jameson,

 Andreas Antonopolous, Tuur DeMeester, Konrad S. Graf, Daniel Krawisz, Pierre Rochard, Saifedean Ammous and Jimmy Song have agreed to republish their essays in this ebook format.
 
The series is a non-technical look at Bitcoin, intended to help newcomers think about how to approach the idea of bitcoin from an historical, economic and theoretical point of view.  My goal is to steer the debate around Bitcoin to a longer time horizon. I hope this might be of interest to you and look forward to hearing your thoughts.

Regards,

John Gleeson

twitter.com/btcbehaviour
21.co/johngleeson

**Comment by jlopp** [comment]
Great; I added to the history section with d7ccbdc and should deploy it in a week or so.
