### ISSUE TITLE
add Crypto Words Bitcoin Journal to Bitcoin History page

### ISSUE THREAD

**Issue by joe-rodgers** [jlopp/lopp.net#380]
Consider adding [Crypto Words Bitcoin Journal](https://cryptowords.github.io/) to the [Bitcoin History page](https://www.lopp.net/bitcoin-information/history.html).

The project's mission is to preserve historical writings and commentary about Bitcoin, which is inline with the purpose of the Bitcoin history page.

[![](https://cryptowords.github.io/assets/images/cryptowords88.png)](https://cryptowords.github.io/)

*Crypto Words* publishes a monthly journal of Bitcoin only blogs, tweets, and essays that you can view in browser or download in .pdf.

You can view the complete catalog [here](https://cryptowords.github.io/categories/journals/).

It has 19 months published and is working backwards adding journals in reverse chronological to catalog as much important Bitcoin writing as possible.

https://cryptowords.github.io/
https://github.com/cryptowords/cryptowords.github.io
https://twitter.com/_cryptowords

**Comment by jlopp** [comment]
Looks good, thanks.
