### ISSUE TITLE
Casa Node is missing from the Bitcoin Full Nodes page!

### ISSUE THREAD

**Issue by nickycutesc** [jlopp/lopp.net#452]
Just noticed that Casa Node is missing from the Bitcoin Full Nodes page:

https://www.lopp.net/bitcoin-information/full-node.html

Is this intentional?

**Comment by jlopp** [comment]
Yes, I removed it because it's no longer for sale. If it manages to get some traction as an open source DIY solution then I'm happy to re-evaluate later.
