### ISSUE TITLE
Articles on lopp.net/articles.html 404

### ISSUE THREAD

**Issue by 0xB10C** [jlopp/lopp.net#462]
Just a quick heads up: Most of the article links on https://www.lopp.net/articles.html are broken/404.

e.g.
- https://www.lopp.net/who-controls-bitcoin-core-/
- https://www.lopp.net/metal-bitcoin-seed-storage-stress-test--part-ii-/
- https://www.lopp.net/griefing-crypto-deleted-tweets/

**Comment by jlopp** [comment]
I noticed this happened for a brief time last weekend when I was making cloudflare changes to my site; is it possible you have a bad cached version?

**Comment by 0xB10C** [comment]
Can reproduce in different browsers and devices. deadlinkchecker.com shows a lot of red as well.

![image](https://user-images.githubusercontent.com/19157360/75388662-ab205780-58e5-11ea-97ab-a80081eece72.png)

**Comment by jlopp** [comment]
This is odd because none of those links exist; they are all blog links to blog.lopp.net...

Perhaps it's a bad / cached DNS entry? Are you able to visit https://blog.lopp.net ?

**Comment by 0xB10C** [comment]
I'm not. Redirects me to https://www.lopp.net/

Let's see if it resolves itself over the night...

**Comment by jlopp** [comment]
Hmmm seems mostly OK though one issue in australia noted here https://www.whatsmydns.net/#A/blog.lopp.net

**Comment by jlopp** [comment]
OK I think I figured it out. The IPV4 DNS was correct but the IPV6 was still broken; that's why only a small number of people were having this issue. Can you try again now?

**Comment by 0xB10C** [comment]
Working now!

**Comment by jlopp** [comment]
Thanks for the heads up.
