### ISSUE TITLE
Split "Miscellaneous Statistics" in two sections: "Miscellaneous Statistics" and "Bitcoin transaction fee estimations"

### ISSUE THREAD

**Issue by lightningnetworkstores** [jlopp/lopp.net#61]
The "Miscellaneous Statistics" section of bitcoin.html includes many references to websites that estimate the bitcoin transaction fee for different urgency levels. I know at least 8 websites that estimate bitcoin transaction fees:

https://whatthefee.io/
https://fees.truelevel.io/#/btc
https://coinb.in/#fees
https://p2sh.info/dashboard/db/fee-estimation?orgId=1&from=now-7d&to=now
http://statoshi.info/dashboard/db/fee-estimates
https://estimatesmartfee.com/json.json
https://twitter.com/bitcoin_fees
https://bitcoinfees.earn.com/

I think there should be a section for this, as there are quite some resources dedicated to this.

**Comment by jlopp** [comment]
added with  a3523bf
