### ISSUE TITLE
add art & music section

### ISSUE THREAD

**Issue by jlopp** [jlopp/lopp.net#633]
music videos https://www.youtube.com/playlist?list=PL3C264C70646796C4
BTC Minstrel https://soundcloud.com/user-480079998

https://kialara.com/

https://cryptograffiti.com/
https://www.phneep.com/
https://cryptoart.com/
https://btcartgallery.com/
https://luchopoletti.com

**Comment by BitcoinQnA** [comment]
21ism.com

**Comment by Zaxounette** [comment]
https://bitpaint.club/ - Streetart and VRworld buillds

**Comment by wullon** [comment]
https://www.pboy-art.com (street art including Bitcoin QRCodes & puzzles ; eg https://www.instagram.com/p/BsV9apHFAib/)
http://thisisludo.com (some Bitcoin related street art pieces ; eg https://www.instagram.com/p/CIT-Bc6i70n/)
https://hodlr.rocks (laser cut Bitcoin art)
https://www.youtube.com/channel/UCo8TWz714UppUrxYoTuDMvw Lil' Bubble, Bitcoin-themed pop songs covers

**Comment by wullon** [comment]
https://youldesign.fr/ (https://youldesign.fr/site/bitcoin-art/)
https://josie.io
https://www.markbernart.com
https://twitter.com/NanuBerks

(not sure if relevant) https://opensea.io/assets?search[query]=bitcoin

**Comment by overdrev** [comment]
@kevinabosch

**Comment by gurelcan** [comment]
year 2012, great lyrics

https://www.youtube.com/watch?v=WdrSP0V-KLg

**Comment by safehodl** [comment]
More art:

https://btcpins.com/product-category/pins/
https://www.mrblock.org/collections/crypto-wall-art
https://www.cryptocloaks.com/

**Comment by xavierfiechter** [comment]
https://twitter.com/teachin_bitcoin  "educational memes"

**Comment by johnsBeharry** [comment]
art
- https://alexaaker.com
- https://bitko.cc
- https://twitter.com/skyler_ws

**Comment by stcole** [comment]
raps:
- https://www.youtube.com/watch?v=34oQx_88rTo
- https://www.youtube.com/watch?v=yY-JsKXCDuw
- https://open.spotify.com/album/11WOqU9k1q5LBv0jFsh5UR?si=7fCylJgSSfWZ9a43mpVk_A

**Comment by artdesignbySF** [comment]
[artdesignbysf.com ](https://artdesignbySF.com) 
[@artdesignbysf ](https://www.twitter.com/artdesignbySF)

**Comment by onedrop** [comment]
https://twitter.com/crayonsmell

**Comment by cryptobauhaus** [comment]
https://opensea.io/collection/cryptobauhaus

Own digital art and if you want, you can get a physical print of your purchased NFT (included with purchase!)

**Comment by RYRSTUDIO** [comment]
I paint on money, i melt coins & i fuckin love it...
instagram.com/ryrstudio

**Comment by henrythedj** [comment]
Bitcoinbadboi - a collaborative visual and musical art meant to interest and on-board no-coiners in a friendly manner and encourage the continued evolution of artistic community connections from 'social media' to 'deplatformed, diversified connections' to ensure the continuation of strong ecosystem and in turn empower the userbase (community) to be unified outside of any one social media and thus have a stronger voice on platform development

Twitter [@bitcoinbadbxi](www.twitter.com/bitcoinbadbxi)
IG [xHondoBrand](www.instagram.com/xhondobrand)
Facebook [@bitcoinbadbxi](www.facebook.com/bitcoinbadbxi)
Discord [@bitcoinbadbxigang](www.bit.ly/bitcoinbadboidiscord)

**Comment by marcusconnor** [comment]
I have changed the URL to my Roller Coaster site.
OLD: https://bitcoinrollercoasterguy.com/
NEW: https://bitcoincoaster.com/
I do have redirects in place but it would be great if you could update the link. Thanks!
