### ISSUE TITLE
moar art

### ISSUE THREAD

**Issue by jlopp** [jlopp/lopp.net#637]
https://www.21hodl.com/portfolio/

https://www.swanbitcoin.com/arsenal/starfury/

https://twitter.com/BitcoinMemeHub

http://www.vonbitcoinart.com/

https://en.pboy-art.com/

**Comment by lucasmoten** [comment]
Denise Magdale is creating a limited series of original art based on buyer prompt
https://www.denisemagdale.com/shop/

Martin Lukas Ostachowski makes some really cool renderings
https://ostachowski.com/
