### ISSUE TITLE
Repeated mention of a Berkeley course 

### ISSUE THREAD

**Issue by Omkarganjale** [jlopp/lopp.net#674]
Under the Online & Offline classes >> technical section, 
the second course, [Bitcoin & Cryptocurrencies - Blockchain at Berkeley](https://www.edx.org/course/cryptocurrencies-bitcoin-and-the-crypto-space) is already mentioned in the website [Bitcoin & Cryptocurrencies](https://blockchain.berkeley.edu/courses/) which is placed above it.

**Comment by jlopp** [comment]
Good catch, thanks!
