### ISSUE TITLE
Including Pamela Morgan's Crypto asset inheritance planning book

### ISSUE THREAD

**Issue by prahaladbelavadi** [jlopp/lopp.net#70]
I'd like to include this book as a reference , but what section would this go under ?

Ref: [Amazon](https://www.amazon.com/Cryptoasset-Inheritance-Planning-Simple-Owners/dp/1947910116/)

**Comment by jlopp** [comment]
Tricky; I've added it under the already linked video by Pamela Morgan in the security section.  9d8b058
