### ISSUE TITLE
Remove lightningconductor BTC>LN service

### ISSUE THREAD

**Issue by zzaappedd** [jlopp/lopp.net#752]
https://github.com/jlopp/lopp.net/blob/1ddc2d2e97a59b8797f3e8db1a74b7c060ad2f61/lightning-information.html#L472

While I patiently wait for my btc to be sent to my lightning channel, on reddit I found enough evidence to stress me about permanent fund loss.
Money should be reliable and this isn't, and shouldn't be recommended.

**Comment by jlopp** [comment]
It sounds what you're talking about is counterparty risk, which exists for almost any exchange service other than the very few atomic swap options. Can you link to examples of folks saying this service took their money and didn't pay it out on chain?

**Comment by zzaappedd** [comment]
Bitcoin I sent has been returned many days after an attempt was made to bridge to lightning. No lightningBTC made it through. But most importantly someone is alive in the back and made an effort to return the funds.
[reddit, hardly proof more like  circumstancial evidence](https://www.reddit.com/search/?q=lightningconductor)
