### ISSUE TITLE
non-english bitcoin resource lists

### ISSUE THREAD

**Issue by jlopp** [jlopp/lopp.net#757]
african languages: https://exonumia.africa/
arabic: https://bitcoinarabic.org/
German: https://aprycot.media/thek
spanish: https://bgeometrics.github.io/bitcoin_bookmarks_es.html
spanish: https://estudiobitcoin.com/
italian: https://github.com/mirserena/risorsebitcoin/blob/main/README.md
swedish: https://www.bitcoinsverige.org/
Portuguese: https://bitcoinheiros.com/intro-bitcoin/
Russian: https://bitcoin-translated.ru/

**Comment by Quizzicarol** [comment]
Usecripto: youtube.com/usecripto
Brazilian channel in portuguese, we are migrating to become bitcoin only.

**Comment by dennisreimann** [comment]
Geman podcasts:
- https://einundzwanzig.space
- https://bitcoinverstehen.info/podcast/
- https://coinspondent.de/honigdachs-der-bitcoin-podcast-aus-leipzig/

German YT-Channels:
- https://youtube.com/c/Blocktrainer/
- https://youtube.com/c/Einundzwanzig-Podcast/

German blog/newsletter:
- https://btc21.de

**Comment by pcarballeda** [comment]
Spanish:

Lunaticoin podcast
https://go.ivoox.com/sq/663697

**Comment by mbombonato** [comment]
> Usecripto: youtube.com/usecripto
> Brazilian channel in portuguese, we are migrating to become bitcoin only.

Really glad to see you are going to focus on Bitcoin only. Your Bitcoin content is really nice, but I had to unsubscribe last week because of the excess of shitcoin content. In Brazil we need more "Bitcoin only" resources. Unfortunately 99% of content creators here are not interest to focus on what really matter. So far, Bitcoinheiros is our only safe place here. Good move girls! ;)

PS: Sorry for hijack the topic.

**Comment by robwijers** [comment]
Dutch (Nederlands):
 btcwiki.nl (Wikipedia explaining bitcoin)
Lekkercryptisch.nl (background articles)

**Comment by dimitris-t** [comment]
Greek Bitcoin FAQ and merchant directory: https://WeAcceptBitcoin.gr

**Comment by Bardesss** [comment]
Bitcoinst.art - Dutch recource list

**Comment by Pindol83** [comment]
Italian resource list:

https://pindol.medium.com/premessa-1e5254a52475

**Comment by saifedean** [comment]
Saifedean.com/Arabic contains the Arabic translation of several articles.

Saifedean.com/thebitcoinstandard contains links to 25 translations of The Bitcoin Standard

**Comment by readmor** [comment]
https://www.atolyebitcoin.com/blogs/news - Recently started to add content hoping to grow

https://anchor.fm/yirmibirbitcoin - Bitcoin-only podcast, trying to record once weekly.

**Comment by lttrest07** [comment]
Spanish Chile https://www.bitcointec.cl/
