### ISSUE TITLE
Add River learn and glossary

### ISSUE THREAD

**Issue by SDWouters** [jlopp/lopp.net#860]
River has ~300 articles covering the basics, markets, storage, mining, tax, and tech. In River learn https://river.com/learn/

And a glossary of about ~400 bitcoin-related, engineering, or financial-related terms explained https://river.com/learn/terms/

Could be worth an addition? 
Full disclosure, I work for River, but my predecessor (still working at the company) produced the vast majority of these.

**Comment by jlopp** [comment]
Added to the "other resources" page!
