### ISSUE TITLE
Add blockonomics to list of blockexplorers

### ISSUE THREAD

**Issue by blockonomics** [jlopp/lopp.net#89]
https://lopp.net/bitcoin.html

https://www.blockonomics.co 

One of the few one to [support bech32](https://blog.blockonomics.co/a-segwit-blockexplorer-47cd516dd8c50)

**Comment by jlopp** [comment]
It's a fine block explorer, though it doesn't have all the advanced features of some other explorers such as digging into the scripts / op_return data
