### ISSUE TITLE
msg verifier tool

### ISSUE THREAD

**Issue by jlopp** [jlopp/lopp.net#944]
https://checkmsg.org/

**Comment by stevenroose** [comment]
It seems like that one doesn't support p2wpkh addresses, though.

**Comment by stevenroose** [comment]
Maybe list https://www.verifybitcoinmessage.com/, it's the only one I can find that supports p2wpkh addressees.

**Comment by stevenroose** [comment]
Of course, [hal](https://github.com/stevenroose/hal/) also supports it.

**Comment by jlopp** [comment]
broke them out into a dedicated section https://www.lopp.net/bitcoin-information/developer-tools.html#message
