### ISSUE TITLE
https://jlopp.github.io not available (404) - so config file generator etc as well

### ISSUE THREAD

**Issue by wintercooled** [jlopp/lopp.net#99]
I get a 404 on jlopp.github.io

So this link on bitcoin.html is down: 

https://jlopp.github.io/bitcoin-core-config-generator/

**Comment by jlopp** [comment]
jlopp.github.io has never hosted anything; the config generator to which you're linking loads fine for me...

**Comment by wintercooled** [comment]
Have tested - doesn't load on Chrome on Mac. Have tested on two macs.

Works on the Mac in other browsers. Works on Chrome on Linux and Windows.

Odd.
